$('.owl-carousel').owlCarousel({
    loop:false,
    margin:5,
    nav:false,
    responsive:{
        0:{
            items:4
        },
        600:{
            items:4
        },
        1000:{
            items:4
        }
    }
})